services:
  gdmt-ms-zuul-server:
    image: plchavez98/gdmt-ms-zuul-server:latest
    container_name: gdmt-ms-zuul-server
    ports:
      - "80:8090"
    environment:
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      PROFILE_ACTIVE: qa
    restart: always
    networks:
      - gdmt-microservices-network
networks:
  gdmt-microservices-network:
    external: true