services:
  gdmt-ms-vault-server:
    image: plchavez98/vault-filesystem:0.2
    container_name: gdmt-ms-vault-server
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    volumes:
      - gdmt_vault_data:/vault/data
    restart: always
    networks:
      - gdmt-microservices-network
volumes:
  gdmt_vault_data:
networks:
  gdmt-microservices-network:
    external: true